### ISSUE TITLE
Doesn't work in 1.8

### ISSUE THREAD

**Issue by siemlohuis** [BanjerHD/AntiSpongeAbsorbtion#1]
[AntiSpongeAbsorbtion] Plugin AntiSpongeAbsorbtion v1.0 has failed to register events for class me.banjer_hd.plugins.antispongeabsorbtion.events.OnSpongeAbsorbtion because org/bukkit/event/block/SpongeAbsorbEvent does not exist.

**Comment by BanjerHD** [comment]
- Test all minecraft versions

**Comment by portlek** [comment]
The event does not exist, you can do that in the certain version.

**Comment by BanjerHD** [comment]
> The event does not exist, you can't do that in the certain version.

Agree, closed

**Comment by BanjerHD** [comment]
KarimAKL on [bukkit.org](https://bukkit.org/threads/disable-sponge-absorption.482538/#post-3611816):

> @Banjer_HD I haven't tested this but, maybe it's worth a try to cancel the BlockPlaceEvent and then set the block using the plugin?

Reopening

TODO: setType(Material.SPONGE, false) <-- false doesn't update blocks

**Comment by BanjerHD** [comment]
setType(Material.SPONGE, false)

false doesn't work with water and still absorbs it

**Comment by BanjerHD** [comment]
Fixed in v1.2 by https://github.com/Zalosath/
Warning: when you update the block it still absorbs it!
